
CREATE DATABASE IF NOT EXISTS urlgz;

USE urlgz;

CREATE TABLE IF NOT EXISTS url_entity (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    short_code VARCHAR(10) UNIQUE NOT NULL,
    original_url TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    click_count BIGINT DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON urlgz.* TO 'user'@'%';
FLUSH PRIVILEGES;

